INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11101', '111', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11201', '112', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11301', '113', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11401', '114', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11501', '115', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11601', '116', 'LT');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11701', '117', 'RU');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11801', '118', 'RU');
INSERT INTO `advanced_task2`.`rating_type` (`RatingTypeId`, `ReportingContextId`, `RatingTypeCode`) VALUES ('11901', '119', 'RU');
