CREATE TABLE `additional_task`.`emp a` (
  `EMPID` INT NOT NULL,
  `EMPNAME` VARCHAR(50) NULL,
  `MGRID` INT NULL,
  `DEPTID` INT NULL,
  `SALARY` DOUBLE NULL,
  `DOB` DATETIME(6) NULL,
  PRIMARY KEY (`EMPID`));
