INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('1', 'Peter', '150');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('2', 'Alice', '950');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('3', 'Ban', '500');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('4', 'Vlad', '600');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('5', 'Bogdan', '990');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('6', 'Bob', '1001');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('7', 'Martin', '999');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('8', 'Alice', '860');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('9', 'Sergii', '1200');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('10', 'Olexandr', '320');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('11', 'Mary', '40');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('12', 'Berta', '1500');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('13', 'Marta', '2000');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('14', 'Robert', '995');
INSERT INTO `advanced_task3`.`empl` (`e_id`, `Name`, `Salary`) VALUES ('15', 'Jonh', '1005');
INSERT INTO `advanced_task3`.`empl` (`e_id`) VALUES ('16');
INSERT INTO `advanced_task3`.`empl` (`e_id`) VALUES ('17');
INSERT INTO `advanced_task3`.`empl` (`e_id`) VALUES ('18');
INSERT INTO `advanced_task3`.`empl` (`e_id`) VALUES ('19');
INSERT INTO `advanced_task3`.`empl` (`e_id`) VALUES ('20');
